# Generated by Django 5.0.2 on 2024-03-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ucontact',
            fields=[
                ('uindex', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=50)),
                ('uemail', models.EmailField(max_length=50)),
                ('usubject', models.CharField(max_length=50)),
                ('umessage', models.TextField()),
            ],
        ),
    ]
